USE [TN_CSDLPT]
GO
/****** Object:  StoredProcedure [dbo].[SP_DanhSachCacMonThi]    Script Date: 26/06/2024 6:55:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROC [dbo].[SP_DanhSachCacMonThi]
@masv char(8)
AS
BEGIN
    DECLARE @malop nchar(15)
    SELECT @malop = MALOP FROM SINHVIEN WHERE MASV = @masv
    SELECT MAMH, TRINHDO, NGAYTHI, LAN, SOCAUTHI, THOIGIAN FROM GIAOVIEN_DANGKY WHERE MALOP = @malop
END