USE [TN_CSDLPT]
GO
/** Object:  StoredProcedure [dbo].[SP_DanhSachDangKyThi]    Script Date: 17/06/2024 3:09:20 PM **/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER   PROCEDURE [dbo].[SP_DanhSachDangKyThi]
@fromDate datetime,
@toDate datetime
AS
BEGIN
SELECT DISTINCT LOP.TENLOP, MONHOC.TENMH, CONCAT(GIAOVIEN.HO,' ',GIAOVIEN.TEN) AS HOTEN, GVDK.SOCAUTHI,
            CONVERT(DATETIME, GVDK.NGAYTHI) AS NGAYTHI, dbo.KT_MonHoc(MONHOC.MAMH) AS DATHI  FROM GIAOVIEN_DANGKY GVDK 
            inner join LOP ON (lOP.MALOP = GVDK.MALOP)
            inner join MONHOC ON (GVDK.MAMH = MONHOC.MAMH)
            inner join GIAOVIEN ON (GVDK.MAGV = GIAOVIEN.MAGV)
            WHERE (GVDK.NGAYTHI BETWEEN @fromDate AND @toDate)
END;