USE [TN_CSDLPT]
GO
/****** Object:  StoredProcedure [dbo].[SP_DanhSachSinhVien]    Script Date: 24/06/2024 3:35:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROC [dbo].[SP_DanhSachSinhVien]
AS
BEGIN
    SELECT MASV, HO, TEN, NGAYSINH, DIACHI, MALOP=(SELECT TENLOP FROM LOP WHERE SINHVIEN.MALOP = LOP.MALOP), MATKHAU
    FROM SINHVIEN
END