USE [TN_CSDLPT]
GO
/****** Object:  StoredProcedure [dbo].[SP_DanhSachLop]    Script Date: 24/06/2024 3:29:01 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROC [dbo].[SP_DanhSachLop]
AS
BEGIN
    SELECT MALOP, TENLOP, (SELECT TENKH FROM KHOA WHERE (LOP.MAKH = MAKH)) AS MAKH
    FROM LOP
END