USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[SP_InBangDiem]    Script Date: 17/06/2024 9:38:48 SA ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROC [dbo].[SP_InBangDiem]
@MALOP NVARCHAR (15),
@MAMONHOC	char(5),
@LANTHI smallint
AS
BEGIN
SELECT SV.MASV, HOTEN=HO + ' ' + TEN, ISNULL(DIEM,0) FROM (SELECT MASV, HO, TEN FROM SINHVIEN  WHERE MALOP = @MALOP) SV 
	LEFT JOIN	--Dùng left join để khi các sv ko thi thì vẫn in ra
		(SELECT MASV, DIEM FROM BANGDIEM WHERE MAMH =@MAMONHOC AND LAN=@LANTHI) DIEM
		ON SV.MASV = DIEM.MASV
END
GO

