USE [TN_CSDLPT]
GO
/****** Object:  StoredProcedure [dbo].[SP_KiemTraMonHocTonTai]    Script Date: 24/06/2024 3:40:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROC [dbo].[SP_KiemTraMonHocTonTai]
@MAMH NCHAR(5), @TENMH NVARCHAR(50)
AS
BEGIN
    IF EXISTS(SELECT MAMH FROM MONHOC WHERE MAMH = @MAMH)
    RAISERROR('Mã môn này đã tồn tại', 16, 1) 
    IF EXISTS(SELECT TENMH FROM MONHOC WHERE TENMH = @TENMH)
    RAISERROR('Tên môn này đã tồn tại', 16, 1) 
END