USE [TN_CSDLPT]
GO
/****** Object:  StoredProcedure [dbo].[SP_KiemTraKhoaTonTai]    Script Date: 24/06/2024 3:39:31 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROC [dbo].[SP_KiemTraKhoaTonTai]
@MAKH NCHAR(8), @TENKH NVARCHAR(50)
AS
BEGIN
    IF EXISTS(SELECT MAKH FROM LINK2.TN_CSDLPT.DBO.KHOA WHERE MAKH = @MAKH)
    RAISERROR('Mã khoa này đã tồn tại', 16, 1) 
    IF EXISTS(SELECT TENKH FROM LINK2.TN_CSDLPT.DBO.KHOA WHERE TENKH = @TENKH)
    RAISERROR('Tên khoa này đã tồn tại', 16, 1) 
END