USE [TN_CSDLPT]
GO
/****** Object:  StoredProcedure [dbo].[SP_DangNhapGiangVien]    Script Date: 03/04/2024 18:08:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE or ALTER PROC [dbo].[SP_DangNhapGiangVien]
@TENLOGIN NVARCHAR (50)
AS
DECLARE @TENUSER NVARCHAR(50)
SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)
 
 SELECT USERNAME = @TENLOGIN, 
  HOTEN = (SELECT HO+ ' '+ TEN FROM dbo.GIAOVIEN  WHERE MAGV = @TENUSER ),
   TENNHOM= NAME
   FROM sys.sysusers 
   WHERE UID = (SELECT MIN(GROUPUID) FROM SYS.SYSMEMBERS WHERE MEMBERUID = (SELECT UID FROM sys.sysusers WHERE NAME = @TENUSER))